# Use root/example as user/password credentials
version: '3.1'

services:
    
  docker-mysql:
    image: mysql:8
    build: .
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_db
      MYSQL_USER: microuser
      MYSQL_PASSWORD: micropw

  microuser:
    image: openjdk:8
    build: .
    ports:
      - 8092:8080
    depends_on:
      - docker-mysql