FROM openjdk:8

RUN mkdir -p /usr/src/microuser

COPY micro-user.jar /usr/src/microuser

WORKDIR /usr/src/microuser

## THE LIFE SAVER
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh

## Launch the wait tool and then your application
CMD ["./wait-for-it.sh", "--timeout=0", "mysql:3306", "--", "java", "-jar", "micro-user.jar"]