version: '3.1'

services:
    
  mysql:
    build:
        context: .
        dockerfile: Dockerfile-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_db
      MYSQL_USER: microuser
      MYSQL_PASSWORD: micropw

  microuser:
    build:
        context: .
        dockerfile: Dockerfile-app
    ports:
      - 8092:8080
    depends_on:
      - mysql